spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名和下划线命名自动转换

path:
  save: C:\Users\Administrator\Desktop\files\
  python_code: D:\JAVA\Python\test.py

name:
  python_method: do_analysis



